version: '3.9'
services:
  worker:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      DB_URI: $DB_URI
      OWNER_ID: $OWNER_ID